import { HashTagData } from '@/types/hashTag';

export const HASH_TAG_LIST: HashTagData[] = [
  { id: 1, tag: '아이디어풍부', type: 'positive' },
  { id: 2, tag: '의견을명확히전달', type: 'positive' },
  { id: 3, tag: '협력적태도', type: 'positive' },
  { id: 4, tag: '문제해결의지', type: 'positive' },
  { id: 5, tag: '끈기있는노력', type: 'positive' },
  { id: 6, tag: '도전적태도', type: 'positive' },
  { id: 7, tag: '논리가명확', type: 'positive' },
  { id: 8, tag: '설득력뛰어남', type: 'positive' },
  { id: 9, tag: '피드백빠름', type: 'positive' },
  { id: 10, tag: '기한준수', type: 'positive' },
  { id: 11, tag: '일정관리잘함', type: 'positive' },
  { id: 12, tag: '친화력좋음', type: 'positive' },
  { id: 13, tag: '리더십뛰어남', type: 'positive' },
  { id: 14, tag: '팀목표에집중', type: 'positive' },
  { id: 15, tag: '문제의새로운접근', type: 'positive' },
  { id: 16, tag: '의견교환어려움', type: 'negative' },
  { id: 17, tag: '팀과소통단절', type: 'negative' },
  { id: 18, tag: '창의성결핍', type: 'negative' },
  { id: 19, tag: '노력부족', type: 'negative' },
  { id: 20, tag: '집중력저하', type: 'negative' },
  { id: 21, tag: '문제에소극적', type: 'negative' },
  { id: 22, tag: '시도조차하지않음', type: 'negative' },
  { id: 23, tag: '집중력부족', type: 'negative' },
  { id: 24, tag: '논리부족', type: 'negative' },
  { id: 25, tag: '설득력떨어짐', type: 'negative' },
  { id: 26, tag: '피드백부족', type: 'negative' },
  { id: 27, tag: '부정적태도', type: 'negative' },
  { id: 28, tag: '소극적참여', type: 'negative' },
  { id: 29, tag: '책임감부족', type: 'negative' },
  { id: 30, tag: '독단적행동', type: 'negative' },
];
